return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "lua",
      "cpp",
      "c",
      "css",
      "c_sharp",
      "html",
      "htmldjango",
      "javascript",
      "json",
      "dart",
      "cpp",
      "python",
      "php",
      "solidity",
      "vue",
      "typescript",
      "sql",
      "prisma",
      "scss",
      "dockerfile",
      "graphql",
    },
  },
}
